//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie_03
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Организация.
    /// </summary>
    // *** Start programmer edit section *** (Организация CustomAttributes)

    // *** End programmer edit section *** (Организация CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОрганизацияE", new string[] {
            "Код as \'Код\'",
            "Наименование as \'Наименование\'",
            "Описание as \'Описание\'"})]
    [View("ОрганизацияL", new string[] {
            "Код as \'Код\'",
            "Наименование as \'Наименование\'",
            "Описание as \'Описание\'"})]
    public class Организация : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private string fНаименование;
        
        private string fОписание;
        
        // *** Start programmer edit section *** (Организация CustomMembers)

        // *** End programmer edit section *** (Организация CustomMembers)

        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (Организация.Код CustomAttributes)

        // *** End programmer edit section *** (Организация.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (Организация.Код Get start)

                // *** End programmer edit section *** (Организация.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (Организация.Код Get end)

                // *** End programmer edit section *** (Организация.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.Код Set start)

                // *** End programmer edit section *** (Организация.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (Организация.Код Set end)

                // *** End programmer edit section *** (Организация.Код Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Организация.Наименование CustomAttributes)

        // *** End programmer edit section *** (Организация.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Организация.Наименование Get start)

                // *** End programmer edit section *** (Организация.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Организация.Наименование Get end)

                // *** End programmer edit section *** (Организация.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.Наименование Set start)

                // *** End programmer edit section *** (Организация.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Организация.Наименование Set end)

                // *** End programmer edit section *** (Организация.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Описание.
        /// </summary>
        // *** Start programmer edit section *** (Организация.Описание CustomAttributes)

        // *** End programmer edit section *** (Организация.Описание CustomAttributes)
        [StrLen(255)]
        public virtual string Описание
        {
            get
            {
                // *** Start programmer edit section *** (Организация.Описание Get start)

                // *** End programmer edit section *** (Организация.Описание Get start)
                string result = this.fОписание;
                // *** Start programmer edit section *** (Организация.Описание Get end)

                // *** End programmer edit section *** (Организация.Описание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.Описание Set start)

                // *** End programmer edit section *** (Организация.Описание Set start)
                this.fОписание = value;
                // *** Start programmer edit section *** (Организация.Описание Set end)

                // *** End programmer edit section *** (Организация.Описание Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОрганизацияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОрганизацияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОрганизацияE", typeof(IIS.Prilozhenie_03.Организация));
                }
            }
            
            /// <summary>
            /// "ОрганизацияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОрганизацияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОрганизацияL", typeof(IIS.Prilozhenie_03.Организация));
                }
            }
        }
    }
}
