//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie_03
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// СтатьиЗатрат.
    /// </summary>
    // *** Start programmer edit section *** (СтатьиЗатрат CustomAttributes)

    // *** End programmer edit section *** (СтатьиЗатрат CustomAttributes)
    [AutoAltered()]
    [Caption("Справочник статьи затрат")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СтатьиЗатратE", new string[] {
            "Код as \'Код\'",
            "Наименование as \'Наименование\'"})]
    [View("СтатьиЗатратL", new string[] {
            "Код as \'Код\'",
            "Наименование as \'Наименование\'"})]
    public class СтатьиЗатрат : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (СтатьиЗатрат CustomMembers)

        // *** End programmer edit section *** (СтатьиЗатрат CustomMembers)

        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (СтатьиЗатрат.Код CustomAttributes)

        // *** End programmer edit section *** (СтатьиЗатрат.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (СтатьиЗатрат.Код Get start)

                // *** End programmer edit section *** (СтатьиЗатрат.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (СтатьиЗатрат.Код Get end)

                // *** End programmer edit section *** (СтатьиЗатрат.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СтатьиЗатрат.Код Set start)

                // *** End programmer edit section *** (СтатьиЗатрат.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (СтатьиЗатрат.Код Set end)

                // *** End programmer edit section *** (СтатьиЗатрат.Код Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (СтатьиЗатрат.Наименование CustomAttributes)

        // *** End programmer edit section *** (СтатьиЗатрат.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (СтатьиЗатрат.Наименование Get start)

                // *** End programmer edit section *** (СтатьиЗатрат.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (СтатьиЗатрат.Наименование Get end)

                // *** End programmer edit section *** (СтатьиЗатрат.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СтатьиЗатрат.Наименование Set start)

                // *** End programmer edit section *** (СтатьиЗатрат.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (СтатьиЗатрат.Наименование Set end)

                // *** End programmer edit section *** (СтатьиЗатрат.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СтатьиЗатратE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СтатьиЗатратE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СтатьиЗатратE", typeof(IIS.Prilozhenie_03.СтатьиЗатрат));
                }
            }
            
            /// <summary>
            /// "СтатьиЗатратL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СтатьиЗатратL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СтатьиЗатратL", typeof(IIS.Prilozhenie_03.СтатьиЗатрат));
                }
            }
        }
    }
}
