//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie_03
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ТЧПлЗНаД.
    /// </summary>
    // *** Start programmer edit section *** (ТЧПлЗНаД CustomAttributes)

    // *** End programmer edit section *** (ТЧПлЗНаД CustomAttributes)
    [AutoAltered()]
    [Caption("Табличная Часть Плановая заявка на день")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧПлЗНаДE", new string[] {
            "СтатьиЗатрат as \'Статья затрат\'",
            "СтатьиЗатрат.Наименование as \'Статья затрат\'",
            "СпрКонтрАг as \'Контрагент\'",
            "СпрКонтрАг.Наименование as \'Контрагент\'",
            "СпрНомен as \'Номенклатура\'",
            "СпрНомен.Наименование as \'Номенклатура\'",
            "СпрВидыРаб as \'Вид работы\'",
            "СпрВидыРаб.Наименование as \'Вид работы\'",
            "ОбРаб as \'Объем работ\'",
            "СпрТранспСр as \'Транспортное средство\'",
            "СпрТранспСр.Наименование as \'Транспортное средство\'",
            "СпрТипТрансСр as \'Тип транспортного средства\'",
            "СпрТипТрансСр.Наименование as \'Тип транспортного средства\'",
            "ВремПриб as \'Время прибытия\'",
            "КолЧас as \'Количество часов работы\'",
            "СпрЕдИзмер as \'Единицы измерения\'",
            "СпрЕдИзмер.Наименование as \'Единицы измерения\'"})]
    [MasterViewDefineAttribute("ТЧПлЗНаДE", "СпрКонтрАг", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Контрагент")]
    [MasterViewDefineAttribute("ТЧПлЗНаДE", "СпрНомен", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номенклатура")]
    [MasterViewDefineAttribute("ТЧПлЗНаДE", "СпрВидыРаб", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Вид работы")]
    [MasterViewDefineAttribute("ТЧПлЗНаДE", "СпрТранспСр", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Транспортное средство")]
    [MasterViewDefineAttribute("ТЧПлЗНаДE", "СпрТипТрансСр", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Тип транспортного средства")]
    [MasterViewDefineAttribute("ТЧПлЗНаДE", "СпрЕдИзмер", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Единицы измерения")]
    public class ТЧПлЗНаД : ICSSoft.STORMNET.DataObject
    {
        
        private float fОбГруз;
        
        private string fОбРаб;
        
        private float fКолЧас;
        
        private System.DateTime fВремПриб;
        
        private IIS.Prilozhenie_03.СтатьиЗатрат fСтатьиЗатрат;
        
        private IIS.Prilozhenie_03.СпрТипТрансСр fСпрТипТрансСр;
        
        private IIS.Prilozhenie_03.СпрТранспСр fСпрТранспСр;
        
        private IIS.Prilozhenie_03.СпрЕдИзмер fСпрЕдИзмер;
        
        private IIS.Prilozhenie_03.СпрНомен fСпрНомен;
        
        private IIS.Prilozhenie_03.СпрВидыРаб fСпрВидыРаб;
        
        private IIS.Prilozhenie_03.СпрКонтрАг fСпрКонтрАг;
        
        private IIS.Prilozhenie_03.ДокПланЗаНаД fДокПланЗаНаД;
        
        // *** Start programmer edit section *** (ТЧПлЗНаД CustomMembers)

        // *** End programmer edit section *** (ТЧПлЗНаД CustomMembers)

        
        /// <summary>
        /// ВремПриб.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПлЗНаД.ВремПриб CustomAttributes)

        // *** End programmer edit section *** (ТЧПлЗНаД.ВремПриб CustomAttributes)
        public virtual System.DateTime ВремПриб
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.ВремПриб Get start)

                // *** End programmer edit section *** (ТЧПлЗНаД.ВремПриб Get start)
                System.DateTime result = this.fВремПриб;
                // *** Start programmer edit section *** (ТЧПлЗНаД.ВремПриб Get end)

                // *** End programmer edit section *** (ТЧПлЗНаД.ВремПриб Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.ВремПриб Set start)

                // *** End programmer edit section *** (ТЧПлЗНаД.ВремПриб Set start)
                this.fВремПриб = value;
                // *** Start programmer edit section *** (ТЧПлЗНаД.ВремПриб Set end)

                // *** End programmer edit section *** (ТЧПлЗНаД.ВремПриб Set end)
            }
        }
        
        /// <summary>
        /// КолЧас.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПлЗНаД.КолЧас CustomAttributes)

        // *** End programmer edit section *** (ТЧПлЗНаД.КолЧас CustomAttributes)
        public virtual float КолЧас
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.КолЧас Get start)

                // *** End programmer edit section *** (ТЧПлЗНаД.КолЧас Get start)
                float result = this.fКолЧас;
                // *** Start programmer edit section *** (ТЧПлЗНаД.КолЧас Get end)

                // *** End programmer edit section *** (ТЧПлЗНаД.КолЧас Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.КолЧас Set start)

                // *** End programmer edit section *** (ТЧПлЗНаД.КолЧас Set start)
                this.fКолЧас = value;
                // *** Start programmer edit section *** (ТЧПлЗНаД.КолЧас Set end)

                // *** End programmer edit section *** (ТЧПлЗНаД.КолЧас Set end)
            }
        }
        
        /// <summary>
        /// ОбГруз.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПлЗНаД.ОбГруз CustomAttributes)

        // *** End programmer edit section *** (ТЧПлЗНаД.ОбГруз CustomAttributes)
        public virtual float ОбГруз
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.ОбГруз Get start)

                // *** End programmer edit section *** (ТЧПлЗНаД.ОбГруз Get start)
                float result = this.fОбГруз;
                // *** Start programmer edit section *** (ТЧПлЗНаД.ОбГруз Get end)

                // *** End programmer edit section *** (ТЧПлЗНаД.ОбГруз Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.ОбГруз Set start)

                // *** End programmer edit section *** (ТЧПлЗНаД.ОбГруз Set start)
                this.fОбГруз = value;
                // *** Start programmer edit section *** (ТЧПлЗНаД.ОбГруз Set end)

                // *** End programmer edit section *** (ТЧПлЗНаД.ОбГруз Set end)
            }
        }
        
        /// <summary>
        /// ОбРаб.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПлЗНаД.ОбРаб CustomAttributes)

        // *** End programmer edit section *** (ТЧПлЗНаД.ОбРаб CustomAttributes)
        [StrLen(255)]
        public virtual string ОбРаб
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.ОбРаб Get start)

                // *** End programmer edit section *** (ТЧПлЗНаД.ОбРаб Get start)
                string result = this.fОбРаб;
                // *** Start programmer edit section *** (ТЧПлЗНаД.ОбРаб Get end)

                // *** End programmer edit section *** (ТЧПлЗНаД.ОбРаб Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.ОбРаб Set start)

                // *** End programmer edit section *** (ТЧПлЗНаД.ОбРаб Set start)
                this.fОбРаб = value;
                // *** Start programmer edit section *** (ТЧПлЗНаД.ОбРаб Set end)

                // *** End programmer edit section *** (ТЧПлЗНаД.ОбРаб Set end)
            }
        }
        
        /// <summary>
        /// ТЧПлЗНаД.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПлЗНаД.СпрВидыРаб CustomAttributes)

        // *** End programmer edit section *** (ТЧПлЗНаД.СпрВидыРаб CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрВидыРаб"})]
        [NotNull()]
        public virtual IIS.Prilozhenie_03.СпрВидыРаб СпрВидыРаб
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрВидыРаб Get start)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрВидыРаб Get start)
                IIS.Prilozhenie_03.СпрВидыРаб result = this.fСпрВидыРаб;
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрВидыРаб Get end)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрВидыРаб Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрВидыРаб Set start)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрВидыРаб Set start)
                this.fСпрВидыРаб = value;
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрВидыРаб Set end)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрВидыРаб Set end)
            }
        }
        
        /// <summary>
        /// ТЧПлЗНаД.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПлЗНаД.СпрЕдИзмер CustomAttributes)

        // *** End programmer edit section *** (ТЧПлЗНаД.СпрЕдИзмер CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрЕдИзмер"})]
        [NotNull()]
        public virtual IIS.Prilozhenie_03.СпрЕдИзмер СпрЕдИзмер
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрЕдИзмер Get start)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрЕдИзмер Get start)
                IIS.Prilozhenie_03.СпрЕдИзмер result = this.fСпрЕдИзмер;
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрЕдИзмер Get end)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрЕдИзмер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрЕдИзмер Set start)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрЕдИзмер Set start)
                this.fСпрЕдИзмер = value;
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрЕдИзмер Set end)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрЕдИзмер Set end)
            }
        }
        
        /// <summary>
        /// ТЧПлЗНаД.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПлЗНаД.СпрКонтрАг CustomAttributes)

        // *** End programmer edit section *** (ТЧПлЗНаД.СпрКонтрАг CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрКонтрАг"})]
        [NotNull()]
        public virtual IIS.Prilozhenie_03.СпрКонтрАг СпрКонтрАг
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрКонтрАг Get start)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрКонтрАг Get start)
                IIS.Prilozhenie_03.СпрКонтрАг result = this.fСпрКонтрАг;
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрКонтрАг Get end)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрКонтрАг Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрКонтрАг Set start)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрКонтрАг Set start)
                this.fСпрКонтрАг = value;
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрКонтрАг Set end)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрКонтрАг Set end)
            }
        }
        
        /// <summary>
        /// ТЧПлЗНаД.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПлЗНаД.СпрНомен CustomAttributes)

        // *** End programmer edit section *** (ТЧПлЗНаД.СпрНомен CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрНомен"})]
        [NotNull()]
        public virtual IIS.Prilozhenie_03.СпрНомен СпрНомен
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрНомен Get start)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрНомен Get start)
                IIS.Prilozhenie_03.СпрНомен result = this.fСпрНомен;
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрНомен Get end)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрНомен Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрНомен Set start)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрНомен Set start)
                this.fСпрНомен = value;
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрНомен Set end)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрНомен Set end)
            }
        }
        
        /// <summary>
        /// ТЧПлЗНаД.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПлЗНаД.СпрТипТрансСр CustomAttributes)

        // *** End programmer edit section *** (ТЧПлЗНаД.СпрТипТрансСр CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрТипТрансСр"})]
        [NotNull()]
        public virtual IIS.Prilozhenie_03.СпрТипТрансСр СпрТипТрансСр
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрТипТрансСр Get start)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрТипТрансСр Get start)
                IIS.Prilozhenie_03.СпрТипТрансСр result = this.fСпрТипТрансСр;
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрТипТрансСр Get end)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрТипТрансСр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрТипТрансСр Set start)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрТипТрансСр Set start)
                this.fСпрТипТрансСр = value;
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрТипТрансСр Set end)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрТипТрансСр Set end)
            }
        }
        
        /// <summary>
        /// ТЧПлЗНаД.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПлЗНаД.СпрТранспСр CustomAttributes)

        // *** End programmer edit section *** (ТЧПлЗНаД.СпрТранспСр CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрТранспСр"})]
        [NotNull()]
        public virtual IIS.Prilozhenie_03.СпрТранспСр СпрТранспСр
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрТранспСр Get start)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрТранспСр Get start)
                IIS.Prilozhenie_03.СпрТранспСр result = this.fСпрТранспСр;
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрТранспСр Get end)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрТранспСр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрТранспСр Set start)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрТранспСр Set start)
                this.fСпрТранспСр = value;
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрТранспСр Set end)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрТранспСр Set end)
            }
        }
        
        /// <summary>
        /// ТЧПлЗНаД.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПлЗНаД.СтатьиЗатрат CustomAttributes)

        // *** End programmer edit section *** (ТЧПлЗНаД.СтатьиЗатрат CustomAttributes)
        [PropertyStorage(new string[] {
                "СтатьиЗатрат"})]
        [NotNull()]
        public virtual IIS.Prilozhenie_03.СтатьиЗатрат СтатьиЗатрат
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.СтатьиЗатрат Get start)

                // *** End programmer edit section *** (ТЧПлЗНаД.СтатьиЗатрат Get start)
                IIS.Prilozhenie_03.СтатьиЗатрат result = this.fСтатьиЗатрат;
                // *** Start programmer edit section *** (ТЧПлЗНаД.СтатьиЗатрат Get end)

                // *** End programmer edit section *** (ТЧПлЗНаД.СтатьиЗатрат Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.СтатьиЗатрат Set start)

                // *** End programmer edit section *** (ТЧПлЗНаД.СтатьиЗатрат Set start)
                this.fСтатьиЗатрат = value;
                // *** Start programmer edit section *** (ТЧПлЗНаД.СтатьиЗатрат Set end)

                // *** End programmer edit section *** (ТЧПлЗНаД.СтатьиЗатрат Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Prilozhenie_03.ДокПланЗаНаД.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПлЗНаД.ДокПланЗаНаД CustomAttributes)

        // *** End programmer edit section *** (ТЧПлЗНаД.ДокПланЗаНаД CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ДокПланЗаНаД"})]
        public virtual IIS.Prilozhenie_03.ДокПланЗаНаД ДокПланЗаНаД
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.ДокПланЗаНаД Get start)

                // *** End programmer edit section *** (ТЧПлЗНаД.ДокПланЗаНаД Get start)
                IIS.Prilozhenie_03.ДокПланЗаНаД result = this.fДокПланЗаНаД;
                // *** Start programmer edit section *** (ТЧПлЗНаД.ДокПланЗаНаД Get end)

                // *** End programmer edit section *** (ТЧПлЗНаД.ДокПланЗаНаД Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.ДокПланЗаНаД Set start)

                // *** End programmer edit section *** (ТЧПлЗНаД.ДокПланЗаНаД Set start)
                this.fДокПланЗаНаД = value;
                // *** Start programmer edit section *** (ТЧПлЗНаД.ДокПланЗаНаД Set end)

                // *** End programmer edit section *** (ТЧПлЗНаД.ДокПланЗаНаД Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧПлЗНаДE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧПлЗНаДE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧПлЗНаДE", typeof(IIS.Prilozhenie_03.ТЧПлЗНаД));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧПлЗНаД.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧПлЗНаД CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧПлЗНаД CustomAttributes)
    public class DetailArrayOfТЧПлЗНаД : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Prilozhenie_03.DetailArrayOfТЧПлЗНаД members)

        // *** End programmer edit section *** (IIS.Prilozhenie_03.DetailArrayOfТЧПлЗНаД members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧПлЗНаД by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧПлЗНаД.
        /// </summary>
        public DetailArrayOfТЧПлЗНаД(IIS.Prilozhenie_03.ДокПланЗаНаД fДокПланЗаНаД) : 
                base(typeof(ТЧПлЗНаД), ((ICSSoft.STORMNET.DataObject)(fДокПланЗаНаД)))
        {
        }
        
        public IIS.Prilozhenie_03.ТЧПлЗНаД this[int index]
        {
            get
            {
                return ((IIS.Prilozhenie_03.ТЧПлЗНаД)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Prilozhenie_03.ТЧПлЗНаД dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
